#!/bin/bash
# embedding モデル整合性マニフェスト（models.sha256）生成スクリプト（TASK-28: revision/hash pinning）。
#
# 指定 model_dir 配下の onnx/model_quantized.onnx, onnx/model.onnx, tokenizer.json の SHA256 を
# 計算し、SDK が include_str! で埋め込むマニフェスト（crates/ygo-search/src/vector/models.sha256）
# を（再）生成する。HF revision（commit SHA）も informational として記録する。
#
# 想定: GNU coreutils の sha256sum（macOS は `brew install coreutils` で `gsha256sum`、
# または `shasum -a 256` を alias してください）。
#
# 使い方:
#   scripts/setup/gen-model-manifest.sh <MODEL_DIR> [OUTPUT_PATH]
#   例: scripts/setup/gen-model-manifest.sh tmp/dev/poc/vector-poc/models/Xenova/multilingual-e5-small

set -e

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <MODEL_DIR> [OUTPUT_PATH]" >&2
    echo "  MODEL_DIR:   multilingual-e5-small を展開したディレクトリ（onnx/, tokenizer.json を含む）" >&2
    echo "  OUTPUT_PATH: 出力先（既定: crates/ygo-search/src/vector/models.sha256）" >&2
    exit 1
fi

MODEL_DIR="$1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${2:-$SCRIPT_DIR/../../crates/ygo-search/src/vector/models.sha256}"
HF_REPO="Xenova/multilingual-e5-small"

# sha256sum（GNU）を優先、無ければ shasum -a 256（macOS）へフォールバック。
SHA256_CMD=""
if command -v sha256sum &> /dev/null; then
    SHA256_CMD="sha256sum -b"
elif command -v shasum &> /dev/null; then
    SHA256_CMD="shasum -a 256"
    echo "注意: sha256sum が無いため shasum -a 256 を使用します（macOS）。" >&2
else
    echo "Error: sha256sum / shasum が見つかりません。GNU coreutils をインストールしてください。" >&2
    exit 1
fi

if [ ! -d "$MODEL_DIR" ]; then
    echo "Error: MODEL_DIR が存在しません: $MODEL_DIR" >&2
    exit 1
fi

# 各モデルファイルの存在確認。
for rel in onnx/model_quantized.onnx onnx/model.onnx tokenizer.json; do
    if [ ! -f "$MODEL_DIR/$rel" ]; then
        echo "Error: $MODEL_DIR/$rel が見つかりません。" >&2
        exit 1
    fi
done

# HF revision（commit SHA）を informational として取得（任意・失敗時は unknown）。
REVISION="unknown"
if command -v curl &> /dev/null; then
    REVISION="$(curl -s "https://huggingface.co/api/models/${HF_REPO}/revision/main" \
        | grep -o '"sha":"[a-f0-9]*"' | head -1 | cut -d'"' -f4 || true)"
fi
if [ -z "$REVISION" ] || [ "$REVISION" = "" ]; then
    REVISION="unknown"
fi

# マニフェスト生成（sha256sum -b 互換の `<hash> *<relpath>` 形式）。
ENTRY_QUANTIZED="$(cd "$MODEL_DIR" && $SHA256_CMD onnx/model_quantized.onnx | cut -d' ' -f1)"
ENTRY_FULL="$(cd "$MODEL_DIR" && $SHA256_CMD onnx/model.onnx | cut -d' ' -f1)"
ENTRY_TOK="$(cd "$MODEL_DIR" && $SHA256_CMD tokenizer.json | cut -d' ' -f1)"

# 出力ディレクトリ作成。
mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" <<EOF
# embedding model integrity manifest (TASK-28: revision/hash pinning)
# SDK はこの manifest を include_str! で埋め込み、ロード時に実ファイルの SHA256 を照合する。
# 脅威モデルは accidental revision overwrite（adversarial TOCTOU は scope 外）。
#
# model: ${HF_REPO}
# revision: ${REVISION}
# source: https://huggingface.co/${HF_REPO}
# generated by scripts/setup/gen-model-manifest.sh
#
# runtime verify targets (Rust の load 経路が使用するファイル):
${ENTRY_QUANTIZED} *onnx/model_quantized.onnx
${ENTRY_FULL} *onnx/model.onnx
${ENTRY_TOK} *tokenizer.json
#
# informational only (Rust の load 経路は使用しない・検証対象外):
#   config.json, tokenizer_config.json
EOF

echo "manifest を生成しました: $OUTPUT" >&2
echo "  onnx/model_quantized.onnx: ${ENTRY_QUANTIZED}" >&2
echo "  onnx/model.onnx:           ${ENTRY_FULL}" >&2
echo "  tokenizer.json:            ${ENTRY_TOK}" >&2
echo "  revision:                  ${REVISION}" >&2
